# Generated by Django 5.1.5 on 2025-01-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255, verbose_name='Site Title')),
                ('favicon', models.FileField(upload_to='logos/favicon/', verbose_name='Favicon')),
                ('logo', models.FileField(upload_to='logos/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_language_name', models.CharField(max_length=2, verbose_name='Language (Short Name TR, EN etc.)')),
                ('language_name', models.CharField(max_length=255, verbose_name='Language Name')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('twohour', 'Two Hour Tour'), ('threehour', 'Three Hour Tour')], default='twohour', max_length=15, verbose_name='Tour Type')),
                ('title_start', models.CharField(max_length=255, verbose_name='Title Start Section (English)')),
                ('description_start', models.TextField(verbose_name='Description Start Section (English)')),
                ('banner_img_start', models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image URL Start Section')),
                ('title_map', models.CharField(max_length=255, verbose_name='Map Title (Tour Type) (English)')),
                ('title_end', models.CharField(max_length=255, verbose_name='Title End Section (English)')),
                ('description_end', models.TextField(verbose_name='Description End Section (English)')),
                ('banner_img_end', models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image URL End Section')),
            ],
            options={
                'verbose_name': 'Section Settings',
                'verbose_name_plural': 'Section Settings',
            },
        ),
        migrations.CreateModel(
            name='SectionSettingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_start', models.CharField(max_length=255, verbose_name='Title Start Section')),
                ('description_start', models.TextField(verbose_name='Description Start Section')),
                ('title_map', models.CharField(max_length=255, verbose_name='Map Title (Tour Type)')),
                ('title_end', models.CharField(max_length=255, verbose_name='Title End Section')),
                ('description_end', models.TextField(verbose_name='Description End Section')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.languagesetting', verbose_name='Language')),
                ('section_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sectionsetting', verbose_name='Site Settings')),
            ],
            options={
                'verbose_name': 'Section Settings Translation',
                'verbose_name_plural': 'Section Settings Translations',
                'unique_together': {('section_setting', 'language')},
            },
        ),
    ]
